#!/usr/bin/env python3
"""Generate catalog.json — the machine-readable input contract for every reusable workflow.

Why this exists: a consuming repo's coding agent should not have to parse ~7,500 lines
of workflow YAML to learn that `deploy-cloudflare-pages` takes `output_dir`. Prose docs
answer that too, but prose drifts — as of 2026-08-11 the docs' own example pins had
spread across twelve different release tags. This file is GENERATED from the shipped
YAML and verified in CI (`--check`), so it cannot drift by construction.

Contracts only. Judgement — which workflow to use, what to watch out for — lives in
AGENTS.md, which is hand-written and links here.

    python3 scripts/gen_catalog.py            # write catalog.json
    python3 scripts/gen_catalog.py --check    # fail if catalog.json is stale
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
WORKFLOWS = ROOT / ".github" / "workflows"
CATALOG = ROOT / "catalog.json"


def _clean(text: str | None) -> str:
    """Collapse YAML folded/multiline descriptions to one line."""
    if not text:
        return ""
    return " ".join(str(text).split())


def contract(path: Path) -> dict | None:
    doc = yaml.safe_load(path.read_text())
    # `on:` parses as boolean True in YAML 1.1 — accept either spelling.
    triggers = doc.get("on", doc.get(True)) or {}
    if "workflow_call" not in triggers:
        return None  # this repo's own CI, not a reusable
    call = triggers["workflow_call"] or {}

    inputs = {}
    for name, spec in (call.get("inputs") or {}).items():
        spec = spec or {}
        inputs[name] = {
            "type": spec.get("type", "string"),
            "required": bool(spec.get("required", False)),
            "default": spec.get("default"),
            "description": _clean(spec.get("description")),
        }

    secrets = {}
    for name, spec in (call.get("secrets") or {}).items():
        spec = spec or {}
        secrets[name] = {
            "required": bool(spec.get("required", False)),
            "description": _clean(spec.get("description")),
        }

    outputs = {
        name: _clean((spec or {}).get("description"))
        for name, spec in (call.get("outputs") or {}).items()
    }

    # What the called workflow's jobs ask for. A job that declares nothing inherits
    # the caller's grant — which is how the badge jobs avoid forcing `contents: write`
    # on callers that do not want it. See DECISIONS.md 2026-08-11.
    jobs = {}
    for job_name, job in (doc.get("jobs") or {}).items():
        jobs[job_name] = {
            "declared_permissions": job.get("permissions", "inherits-caller"),
            "conditional": "if" in job,
        }

    return {
        "workflow": path.name,
        "path": f".github/workflows/{path.name}",
        "name": doc.get("name", path.stem),
        "inputs": inputs,
        "secrets": secrets,
        "outputs": outputs,
        "jobs": jobs,
    }


def build() -> dict:
    entries = {}
    for path in sorted(WORKFLOWS.glob("*.yml")):
        c = contract(path)
        if c:
            entries[path.stem] = c
    return {
        "$comment": (
            "GENERATED by scripts/gen_catalog.py from the shipped workflow YAML — "
            "do not hand-edit; CI verifies it. Contracts only: see AGENTS.md for "
            "which workflow to use and the gotchas. Resolve the version to pin at "
            "read time (gh release view --json tagName); it is deliberately absent here "
            "so this file cannot go stale between releases."
        ),
        "workflows": entries,
    }


def main() -> int:
    fresh = json.dumps(build(), indent=2, sort_keys=True) + "\n"
    if "--check" in sys.argv:
        if not CATALOG.exists():
            print("::error::catalog.json is missing — run scripts/gen_catalog.py")
            return 1
        if CATALOG.read_text() != fresh:
            print(
                "::error::catalog.json is stale — a workflow's input contract changed "
                "without regenerating it. Run: python3 scripts/gen_catalog.py"
            )
            return 1
        print(f"catalog.json is current ({len(build()['workflows'])} workflows)")
        return 0
    CATALOG.write_text(fresh)
    print(f"wrote {CATALOG.relative_to(ROOT)} ({len(build()['workflows'])} workflows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
